import type { User, UsersResponse } from "@shared/api"
import type { RequestHandler } from "express"

const mockUsers: User[] = [
	{
		id: "1",
		name: "Alice Johnson",
		email: "alice.johnson@example.com",
		role: "Admin",
		status: "Active",
		profilePicture: "https://api.dicebear.com/7.x/avataaars/svg?seed=Alice",
	},
	{
		id: "2",
		name: "Bob Smith",
		email: "bob.smith@example.com",
		role: "Editor",
		status: "Active",
		profilePicture: "https://api.dicebear.com/7.x/avataaars/svg?seed=Bob",
	},
	{
		id: "3",
		name: "Carol Williams",
		email: "carol.williams@example.com",
		role: "Viewer",
		status: "Active",
		profilePicture: "https://api.dicebear.com/7.x/avataaars/svg?seed=Carol",
	},
	{
		id: "4",
		name: "David Brown",
		email: "david.brown@example.com",
		role: "Editor",
		status: "Inactive",
		profilePicture: "https://api.dicebear.com/7.x/avataaars/svg?seed=David",
	},
	{
		id: "5",
		name: "Emma Davis",
		email: "emma.davis@example.com",
		role: "Admin",
		status: "Active",
		profilePicture: "https://api.dicebear.com/7.x/avataaars/svg?seed=Emma",
	},
	{
		id: "6",
		name: "Frank Miller",
		email: "frank.miller@example.com",
		role: "Viewer",
		status: "Active",
		profilePicture: "https://api.dicebear.com/7.x/avataaars/svg?seed=Frank",
	},
	{
		id: "7",
		name: "Grace Lee",
		email: "grace.lee@example.com",
		role: "Editor",
		status: "Active",
		profilePicture: "https://api.dicebear.com/7.x/avataaars/svg?seed=Grace",
	},
	{
		id: "8",
		name: "Henry Wilson",
		email: "henry.wilson@example.com",
		role: "Admin",
		status: "Active",
		profilePicture: "https://api.dicebear.com/7.x/avataaars/svg?seed=Henry",
	},
	{
		id: "9",
		name: "Iris Martinez",
		email: "iris.martinez@example.com",
		role: "Editor",
		status: "Active",
		profilePicture: "https://api.dicebear.com/7.x/avataaars/svg?seed=Iris",
	},
	{
		id: "10",
		name: "Jack Anderson",
		email: "jack.anderson@example.com",
		role: "Viewer",
		status: "Active",
		profilePicture: "https://api.dicebear.com/7.x/avataaars/svg?seed=Jack",
	},
	{
		id: "11",
		name: "Karen Thomas",
		email: "karen.thomas@example.com",
		role: "Admin",
		status: "Inactive",
		profilePicture: "https://api.dicebear.com/7.x/avataaars/svg?seed=Karen",
	},
	{
		id: "12",
		name: "Leo Garcia",
		email: "leo.garcia@example.com",
		role: "Editor",
		status: "Active",
		profilePicture: "https://api.dicebear.com/7.x/avataaars/svg?seed=Leo",
	},
	{
		id: "13",
		name: "Monica Jackson",
		email: "monica.jackson@example.com",
		role: "Viewer",
		status: "Active",
		profilePicture: "https://api.dicebear.com/7.x/avataaars/svg?seed=Monica",
	},
	{
		id: "14",
		name: "Nathan White",
		email: "nathan.white@example.com",
		role: "Editor",
		status: "Active",
		profilePicture: "https://api.dicebear.com/7.x/avataaars/svg?seed=Nathan",
	},
	{
		id: "15",
		name: "Olivia Harris",
		email: "olivia.harris@example.com",
		role: "Admin",
		status: "Active",
		profilePicture: "https://api.dicebear.com/7.x/avataaars/svg?seed=Olivia",
	},
	{
		id: "16",
		name: "Peter Martin",
		email: "peter.martin@example.com",
		role: "Viewer",
		status: "Inactive",
		profilePicture: "https://api.dicebear.com/7.x/avataaars/svg?seed=Peter",
	},
	{
		id: "17",
		name: "Quinn Taylor",
		email: "quinn.taylor@example.com",
		role: "Editor",
		status: "Active",
		profilePicture: "https://api.dicebear.com/7.x/avataaars/svg?seed=Quinn",
	},
	{
		id: "18",
		name: "Rachel Rodriguez",
		email: "rachel.rodriguez@example.com",
		role: "Admin",
		status: "Active",
		profilePicture: "https://api.dicebear.com/7.x/avataaars/svg?seed=Rachel",
	},
	{
		id: "19",
		name: "Samuel Clark",
		email: "samuel.clark@example.com",
		role: "Viewer",
		status: "Active",
		profilePicture: "https://api.dicebear.com/7.x/avataaars/svg?seed=Samuel",
	},
	{
		id: "20",
		name: "Tina Lewis",
		email: "tina.lewis@example.com",
		role: "Editor",
		status: "Active",
		profilePicture: "https://api.dicebear.com/7.x/avataaars/svg?seed=Tina",
	},
	{
		id: "21",
		name: "Uma Patel",
		email: "uma.patel@example.com",
		role: "Admin",
		status: "Active",
		profilePicture: "https://api.dicebear.com/7.x/avataaars/svg?seed=Uma",
	},
	{
		id: "22",
		name: "Victor Bell",
		email: "victor.bell@example.com",
		role: "Viewer",
		status: "Active",
		profilePicture: "https://api.dicebear.com/7.x/avataaars/svg?seed=Victor",
	},
	{
		id: "23",
		name: "Wendy Green",
		email: "wendy.green@example.com",
		role: "Editor",
		status: "Inactive",
		profilePicture: "https://api.dicebear.com/7.x/avataaars/svg?seed=Wendy",
	},
	{
		id: "24",
		name: "Xavier Hall",
		email: "xavier.hall@example.com",
		role: "Admin",
		status: "Active",
		profilePicture: "https://api.dicebear.com/7.x/avataaars/svg?seed=Xavier",
	},
	{
		id: "25",
		name: "Yara Young",
		email: "yara.young@example.com",
		role: "Viewer",
		status: "Active",
		profilePicture: "https://api.dicebear.com/7.x/avataaars/svg?seed=Yara",
	},
	{
		id: "26",
		name: "Zachary King",
		email: "zachary.king@example.com",
		role: "Editor",
		status: "Active",
		profilePicture: "https://api.dicebear.com/7.x/avataaars/svg?seed=Zachary",
	},
	{
		id: "27",
		name: "Amy Wright",
		email: "amy.wright@example.com",
		role: "Admin",
		status: "Active",
		profilePicture: "https://api.dicebear.com/7.x/avataaars/svg?seed=Amy",
	},
	{
		id: "28",
		name: "Brian Lopez",
		email: "brian.lopez@example.com",
		role: "Viewer",
		status: "Inactive",
		profilePicture: "https://api.dicebear.com/7.x/avataaars/svg?seed=Brian",
	},
	{
		id: "29",
		name: "Chloe Scott",
		email: "chloe.scott@example.com",
		role: "Editor",
		status: "Active",
		profilePicture: "https://api.dicebear.com/7.x/avataaars/svg?seed=Chloe",
	},
	{
		id: "30",
		name: "Derek Green",
		email: "derek.green@example.com",
		role: "Admin",
		status: "Active",
		profilePicture: "https://api.dicebear.com/7.x/avataaars/svg?seed=Derek",
	},
]

export const handleGetUsers: RequestHandler = (_req, res) => {
	const response: UsersResponse = {
		users: mockUsers,
	}
	res.json(response)
}
